# Generated by Django 4.2.16 on 2024-11-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_order_seller_order_shop_alter_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecommerceuser'),
        ),
    ]
