# Generated by Django 4.2.16 on 2024-11-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_cart_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecommerceuser'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
