# Generated by Django 4.2.16 on 2024-11-20 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tester', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Test User',
                'verbose_name_plural': 'Test Users',
            },
            bases=('authentication.user',),
        ),
    ]
