# Generated by Django 4.2.16 on 2024-11-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuser',
            old_name='tester',
            new_name='test',
        ),
    ]
