# Generated by Django 4.2.17 on 2024-12-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marketplace User',
                'verbose_name_plural': 'Marketplace Users',
            },
            bases=('authentication.user',),
        ),
    ]
