# Generated by Django 4.2.16 on 2024-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('global', 'Global User'), ('ecommerce', 'Ecommerce App User'), ('test', 'Test App User')], default='global', max_length=50),
        ),
    ]
