# Generated by Django 4.2.16 on 2024-11-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_address_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='authentication.usergroup', verbose_name='groups'),
        ),
    ]
